WANDB_PROJECT = "DDPM"
RAW_DATA_ART = "tiny-imagenet_raw"
PROCESSED_DATA_ART = "tiny-imgnt-with-google-extra-resized"
TRAINED_MODEL_ART = "unet-tiny-imagenet"
TRAINING_RUN_NAME = "tiny-imagenet-baseline"
OUTPUT_ART = "diffusion-outputs"
